dist: xenial
language: python
python:
- '3.5'
addons:
  apt:
    packages:
      - python3-pip
      - python-libtorrent
sudo: required
before_install:
      - python -m pip install --upgrade pip && pip install -r requirements.txt
      - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
      - sudo apt-get install nodejs -y
install:
  - sudo pip3 install -r requirements.txt
  
script: 
  - pytest --cov=JavPy --ignore=JavPy/app/web tests/test_clients/
  - codecov
