name: Regular Test

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    name: ${{ matrix.python-version }} @ ${{ matrix.platform }}
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macOS-latest]
        python: [3.5, 3.6, 3.7, 3.8]
        
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set Node.js 12.x
      uses: actions/setup-node@v1.1.0
      with:
        version: 12.x

    - name: Set up Python ${{ matrix.python }} on ${{ matrix.platform }}
      uses: actions/setup-python@v1.0.0
      with:
        version: ${{ matrix.python }}

    - name: Install dependencies on Python ${{ matrix.python }} on ${{ matrix.platform }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r test-requirements.txt

    - name: Test with pytest
      run: pytest -n 4 --looponfail --ignore=JavPy/app/web JavPy/tests/test_clients/
